import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    include: [
      "tests/electron-contract.test.ts",
      "tests/electron-search-contract.test.ts",
      "tests/phase5-prompt-compiler-contract.test.ts",
      "tests/phase8-export-contract.test.ts",
      "tests/electron-migration.test.ts",
      "tests/openai-key-store.test.ts",
      "tests/llm-prompt-compiler.test.ts",
      "tests/llm-prompt-quality.test.ts",
      "tests/phase9-contract.test.ts",
      "tests/phase14-prompt-quality-guardrails.test.ts",
      "tests/electron-persistence.test.ts",
      "tests/electron-search-contract.test.ts",
      "tests/electron-search-persistence.test.ts",
      "tests/project-context-profile.test.ts",
      "tests/prompt-compiler.test.ts",
      "tests/prompt-compiler-draft-review.test.ts",
      "tests/prompt-quality-llm-affordance.test.ts",
      "tests/prompt-quality-persistence.test.ts",
      "tests/prompt-quality-service.test.ts",
      "tests/prompt-quality.test.ts",
      "tests/prompt-quality-ui-panel.test.ts",
      "tests/prompt-quality-renderer.test.ts",
      "tests/prompt-quality-score-provenance.test.ts",
      "tests/prompt-version-diff.test.ts",
      "tests/prompt-scope.test.ts",
      "tests/prompt-export-formatters.test.ts",
      "tests/ui-utils.test.ts",
    ],
    environment: "node",
  },
})
