import { z } from "zod"

export const expectedTables = [
  "projects",
  "project_context_profiles",
  "prompt_assets",
  "prompt_versions",
  "prompt_quality_reviews",
  "prompt_templates",
  "tags",
  "prompt_tags",
  "harness_templates",
  "settings",
] as const

export const forbiddenTables = [
  "prompt_asset_lineage",
  "prompt_runs",
  "agent_runs",
  "execution_results",
  "validation_results",
  "run_logs",
  "clipboard_history",
  "quick_capture_settings",
  "quick_capture_preferences",
  "quick_capture_drafts",
] as const

export const forbiddenHarnessTemplateColumns = ["description", "is_builtin", "is_archived"] as const

export const forbiddenPromptTemplateColumns = [
  "variables",
  "tags",
  "templated_from",
  "improved_from_review",
] as const

export const expectedColumns = {
  projects: [
    "id",
    "name",
    "description",
    "tech_stack",
    "default_agent",
    "created_at",
    "updated_at",
  ],
  project_context_profiles: [
    "id",
    "project_id",
    "name",
    "summary",
    "tech_stack",
    "architecture_notes",
    "coding_conventions",
    "constraints",
    "forbidden_actions",
    "acceptance_defaults",
    "validation_commands",
    "security_notes",
    "additional_context",
    "testing_notes",
    "package_manager",
    "default_branch",
    "repo_path",
    "is_default",
    "created_at",
    "updated_at",
  ],
  prompt_assets: [
    "id",
    "project_id",
    "title",
    "scenario",
    "target_agent",
    "current_version_id",
    "parent_prompt_id",
    "parent_prompt_version_id",
    "derivation_type",
    "created_at",
    "updated_at",
  ],
  prompt_versions: [
    "id",
    "prompt_asset_id",
    "version_number",
    "original_input",
    "compiled_prompt",
    "assumptions",
    "questions",
    "answers",
    "acceptance_criteria",
    "validation_commands",
    "quality_score",
    "created_at",
  ],
  prompt_quality_reviews: [
    "id",
    "prompt_version_id",
    "source",
    "review_mode",
    "overall_score",
    "grade",
    "dimension_scores",
    "strengths",
    "issues",
    "suggestions",
    "missing_sections",
    "warnings",
    "recommended_clarifying_questions",
    "score_explanation",
    "snapshot",
    "improved_prompt_draft",
    "created_at",
  ],
  prompt_templates: [
    "id",
    "name",
    "description",
    "source_prompt_asset_id",
    "source_prompt_version_id",
    "scenario",
    "target_agent",
    "template_body",
    "created_at",
    "updated_at",
  ],
  tags: ["id", "name", "created_at"],
  prompt_tags: ["prompt_asset_id", "tag_id"],
  harness_templates: [
    "id",
    "name",
    "scenario",
    "target_agent",
    "template_body",
    "required_fields",
    "clarification_policy",
    "created_at",
    "updated_at",
  ],
  settings: ["key", "value", "updated_at"],
} as const

export const stringArraySchema = z.array(z.string())
